# Generated by Django 6.0.2 on 2026-03-09 16:58

import ldnf.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ldnf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', ldnf.models.GerenciadorDeUsuarios()),
            ],
        ),
    ]
