# Generated by Django 6.0.2 on 2026-03-18 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ldnf', '0002_alter_usuario_managers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jogador',
        ),
        migrations.DeleteModel(
            name='Time',
        ),
    ]
