# Generated by Django 6.0.2 on 2026-03-18 19:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('localidade', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('escudo', models.URLField(blank=True)),
                ('jogos', models.IntegerField()),
                ('vitorias', models.IntegerField()),
                ('derrotas', models.IntegerField()),
                ('empate', models.IntegerField()),
            ],
        ),
    ]
