# Generated by Django 6.0.3 on 2026-03-19 14:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='derrotas',
        ),
        migrations.RemoveField(
            model_name='time',
            name='empate',
        ),
        migrations.RemoveField(
            model_name='time',
            name='jogos',
        ),
        migrations.RemoveField(
            model_name='time',
            name='vitorias',
        ),
        migrations.CreateModel(
            name='Placar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jogos', models.IntegerField()),
                ('vitorias', models.IntegerField()),
                ('derrotas', models.IntegerField()),
                ('empate', models.IntegerField()),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.time')),
            ],
        ),
    ]
