# Generated by Django 6.0.3 on 2026-03-19 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_remove_time_derrotas_remove_time_empate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placar',
            old_name='nome',
            new_name='time',
        ),
    ]
