# Generated by Django 6.0.3 on 2026-03-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_rename_nome_placar_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='placar',
            name='GM',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='placar',
            name='GS',
            field=models.IntegerField(default=0),
        ),
    ]
