# Generated by Django 6.0.3 on 2026-03-23 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_remove_jogador_time'),
        ('teams', '0004_placar_gm_placar_gs'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='jogadores',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_jogadores', to='players.jogador'),
        ),
    ]
