# Generated by Django 6.0.3 on 2026-03-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_remove_jogador_time'),
        ('teams', '0006_alter_time_jogadores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='jogadores',
        ),
        migrations.AddField(
            model_name='time',
            name='jogadores',
            field=models.ManyToManyField(blank=True, null=True, related_name='time', to='players.jogador'),
        ),
    ]
