# Generated by Django 6.0.3 on 2026-03-27 17:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_remove_time_jogadores_time_jogadores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gols_casa', models.IntegerField()),
                ('gols_visitante', models.IntegerField()),
                ('data_jogo', models.DateTimeField()),
                ('time_casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casa', to='teams.time')),
                ('time_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitante', to='teams.time')),
            ],
        ),
    ]
