# Generated by Django 6.0.2 on 2026-03-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutldnf',
            old_name='sobre_ldnf',
            new_name='titulo',
        ),
        migrations.AlterField(
            model_name='aboutldnf',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
