# Generated by Django 6.0.2 on 2026-03-18 16:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_sobre_ldnf_aboutldnf_titulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutldnf',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
